/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ActionResponseOutput,
  GlobalErrorResponseOutput,
  UpdateNotificationsDtoOutput,
  UpdateProfileDtoOutput,
  UserControllerGetActivityParams,
  UserControllerUploadAvatarBody,
  UserResponseOutput,
} from '../../schemas';

import { instance } from '../../instance';
import type { ErrorType, BodyType } from '../../instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Возвращает полную структуру профиля, включая вложенные объекты безопасности и настроек.
 * @summary Получить профиль текущего пользователя
 */
export const userControllerGetProfile = (
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<UserResponseOutput>({ url: `/api/v1/users/me`, method: 'GET', signal }, options);
};

export const getUserControllerGetProfileQueryKey = () => {
  return [`/api/v1/users/me`] as const;
};

export const getUserControllerGetProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>
  >;
  request?: SecondParameter<typeof instance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerGetProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetProfile>>> = ({
    signal,
  }) => userControllerGetProfile(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerGetProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetProfile>>
>;
export type UserControllerGetProfileQueryError = ErrorType<GlobalErrorResponseOutput>;

export function useUserControllerGetProfile<
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetProfile>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerGetProfile<
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetProfile>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerGetProfile<
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить профиль текущего пользователя
 */

export function useUserControllerGetProfile<
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerGetProfileQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Позволяет точечно обновить имя, bio, часовой пояс и язык интерфейса.
 * @summary Обновить данные профиля
 */
export const userControllerUpdateProfile = (
  updateProfileDtoOutput: BodyType<UpdateProfileDtoOutput>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    {
      url: `/api/v1/users/me`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateProfileDtoOutput,
      signal,
    },
    options
  );
};

export const getUserControllerUpdateProfileMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerUpdateProfile>>,
    TError,
    { data: BodyType<UpdateProfileDtoOutput> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerUpdateProfile>>,
  TError,
  { data: BodyType<UpdateProfileDtoOutput> },
  TContext
> => {
  const mutationKey = ['userControllerUpdateProfile'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerUpdateProfile>>,
    { data: BodyType<UpdateProfileDtoOutput> }
  > = (props) => {
    const { data } = props ?? {};

    return userControllerUpdateProfile(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerUpdateProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpdateProfile>>
>;
export type UserControllerUpdateProfileMutationBody = BodyType<UpdateProfileDtoOutput>;
export type UserControllerUpdateProfileMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Обновить данные профиля
 */
export const useUserControllerUpdateProfile = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerUpdateProfile>>,
      TError,
      { data: BodyType<UpdateProfileDtoOutput> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerUpdateProfile>>,
  TError,
  { data: BodyType<UpdateProfileDtoOutput> },
  TContext
> => {
  return useMutation(getUserControllerUpdateProfileMutationOptions(options), queryClient);
};
/**
 * Частичное обновление настроек email и push уведомлений.
 * @summary Обновить настройки уведомлений
 */
export const userControllerUpdateNotifications = (
  updateNotificationsDtoOutput: BodyType<UpdateNotificationsDtoOutput>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    {
      url: `/api/v1/users/me/notifications`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateNotificationsDtoOutput,
      signal,
    },
    options
  );
};

export const getUserControllerUpdateNotificationsMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerUpdateNotifications>>,
    TError,
    { data: BodyType<UpdateNotificationsDtoOutput> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerUpdateNotifications>>,
  TError,
  { data: BodyType<UpdateNotificationsDtoOutput> },
  TContext
> => {
  const mutationKey = ['userControllerUpdateNotifications'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerUpdateNotifications>>,
    { data: BodyType<UpdateNotificationsDtoOutput> }
  > = (props) => {
    const { data } = props ?? {};

    return userControllerUpdateNotifications(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerUpdateNotificationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpdateNotifications>>
>;
export type UserControllerUpdateNotificationsMutationBody = BodyType<UpdateNotificationsDtoOutput>;
export type UserControllerUpdateNotificationsMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Обновить настройки уведомлений
 */
export const useUserControllerUpdateNotifications = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerUpdateNotifications>>,
      TError,
      { data: BodyType<UpdateNotificationsDtoOutput> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerUpdateNotifications>>,
  TError,
  { data: BodyType<UpdateNotificationsDtoOutput> },
  TContext
> => {
  return useMutation(getUserControllerUpdateNotificationsMutationOptions(options), queryClient);
};
/**
 * Возвращает список последних действий пользователя (логи).
 * @summary Получить ленту активности пользователя
 */
export const userControllerGetActivity = (
  params?: UserControllerGetActivityParams,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<unknown>(
    { url: `/api/v1/users/me/activity`, method: 'GET', params, signal },
    options
  );
};

export const getUserControllerGetActivityQueryKey = (params?: UserControllerGetActivityParams) => {
  return [`/api/v1/users/me/activity`, ...(params ? [params] : [])] as const;
};

export const getUserControllerGetActivityQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetActivity>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  params?: UserControllerGetActivityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetActivity>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerGetActivityQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetActivity>>> = ({
    signal,
  }) => userControllerGetActivity(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetActivity>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerGetActivityQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetActivity>>
>;
export type UserControllerGetActivityQueryError = ErrorType<GlobalErrorResponseOutput>;

export function useUserControllerGetActivity<
  TData = Awaited<ReturnType<typeof userControllerGetActivity>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  params: undefined | UserControllerGetActivityParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetActivity>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetActivity>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetActivity>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerGetActivity<
  TData = Awaited<ReturnType<typeof userControllerGetActivity>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  params?: UserControllerGetActivityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetActivity>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetActivity>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetActivity>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerGetActivity<
  TData = Awaited<ReturnType<typeof userControllerGetActivity>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  params?: UserControllerGetActivityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetActivity>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить ленту активности пользователя
 */

export function useUserControllerGetActivity<
  TData = Awaited<ReturnType<typeof userControllerGetActivity>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  params?: UserControllerGetActivityParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetActivity>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerGetActivityQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Загрузка файла изображения для профиля пользователя.
 * @summary Загрузить новую аватарку
 */
export const userControllerUploadAvatar = (
  userControllerUploadAvatarBody: BodyType<UserControllerUploadAvatarBody>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  const formData = new FormData();
  if (userControllerUploadAvatarBody.file !== undefined) {
    formData.append(`file`, userControllerUploadAvatarBody.file);
  }

  return instance<ActionResponseOutput>(
    { url: `/api/v1/users/me/avatar`, method: 'POST', data: formData, signal },
    options
  );
};

export const getUserControllerUploadAvatarMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerUploadAvatar>>,
    TError,
    { data: BodyType<UserControllerUploadAvatarBody> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerUploadAvatar>>,
  TError,
  { data: BodyType<UserControllerUploadAvatarBody> },
  TContext
> => {
  const mutationKey = ['userControllerUploadAvatar'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerUploadAvatar>>,
    { data: BodyType<UserControllerUploadAvatarBody> }
  > = (props) => {
    const { data } = props ?? {};

    return userControllerUploadAvatar(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerUploadAvatarMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUploadAvatar>>
>;
export type UserControllerUploadAvatarMutationBody = BodyType<UserControllerUploadAvatarBody>;
export type UserControllerUploadAvatarMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Загрузить новую аватарку
 */
export const useUserControllerUploadAvatar = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerUploadAvatar>>,
      TError,
      { data: BodyType<UserControllerUploadAvatarBody> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerUploadAvatar>>,
  TError,
  { data: BodyType<UserControllerUploadAvatarBody> },
  TContext
> => {
  return useMutation(getUserControllerUploadAvatarMutationOptions(options), queryClient);
};
