import { TTeam } from 'entities/team';

export const members: TTeam.TeamMemberResponse[] = [
  {
    id: '1',
    fullName: 'Elena Voss',
    firstName: 'Elena',
    lastName: 'Voss',
    role: 'admin',
    status: 'active',
    avatarUrl: null,
    initials: 'EV',
    joinedAt: '2024-01-15T09:00:00.000Z',
  },
  {
    id: '2',
    fullName: 'Marcus Chen',
    firstName: 'Marcus',
    lastName: 'Chen',
    role: 'lead',
    status: 'active',
    avatarUrl: null,
    initials: 'MC',
    joinedAt: '2024-02-03T10:30:00.000Z',
  },
  {
    id: '3',
    fullName: 'Priya Natarajan',
    firstName: 'Priya',
    lastName: 'Natarajan',
    role: 'member',
    status: 'inactive',
    avatarUrl: null,
    initials: 'PN',
    joinedAt: '2024-03-20T08:15:00.000Z',
  },
  {
    id: '4',
    fullName: 'Jonas Bauer',
    firstName: 'Jonas',
    lastName: 'Bauer',
    role: 'moderator',
    status: 'active',
    avatarUrl: null,
    initials: 'JB',
    joinedAt: '2024-04-01T11:00:00.000Z',
  },
  {
    id: '5',
    fullName: 'Aiko Tanaka',
    firstName: 'Aiko',
    lastName: 'Tanaka',
    role: 'member',
    status: 'inactive',
    avatarUrl: null,
    initials: 'AT',
    joinedAt: '2024-05-10T14:00:00.000Z',
  },
  {
    id: '6',
    fullName: 'Daniel Okafor',
    firstName: 'Daniel',
    lastName: 'Okafor',
    role: 'member',
    status: 'banned',
    avatarUrl: null,
    initials: 'DO',
    joinedAt: '2024-06-22T09:45:00.000Z',
  },
  {
    id: '7',
    fullName: 'Sofia Romano',
    firstName: 'Sofia',
    lastName: 'Romano',
    role: 'member',
    status: 'active',
    avatarUrl: null,
    initials: 'SR',
    joinedAt: '2024-07-08T13:20:00.000Z',
  },
  {
    id: '8',
    fullName: "Liam O'Brien",
    firstName: 'Liam',
    lastName: "O'Brien",
    role: 'member',
    status: 'inactive',
    avatarUrl: null,
    initials: 'LO',
    joinedAt: '2024-08-19T16:00:00.000Z',
  },
];

export const invites: TTeam.TeamInvitationResponse[] = [
  {
    code: 'inv_1f4a8c2b',
    teamId: 'team_01',
    teamName: 'Acme Product Team',
    teamAvatar: null,
    email: 'rahul.shah@acme.io',
    role: 'member',
    inviterId: 'usr_01',
    inviterName: 'Elena Voss',
    createdAt: '2026-05-06T12:00:00.000Z',
    expiresAt: '2026-05-07T12:00:00.000Z',
  },
  {
    code: 'inv_8b6d13ea',
    teamId: 'team_01',
    teamName: 'Acme Product Team',
    teamAvatar: null,
    email: 'noor.amin@acme.io',
    role: 'member',
    inviterId: 'usr_02',
    inviterName: 'Marcus Chen',
    createdAt: '2026-05-06T09:30:00.000Z',
    expiresAt: '2026-05-07T09:30:00.000Z',
  },
  {
    code: 'inv_c9127d4f',
    teamId: 'team_01',
    teamName: 'Acme Product Team',
    teamAvatar: null,
    email: 'kai.lindgren@acme.io',
    role: 'lead',
    inviterId: 'usr_01',
    inviterName: 'Elena Voss',
    createdAt: '2026-05-05T12:00:00.000Z',
    expiresAt: '2026-05-06T18:00:00.000Z',
  },
];

export const roles: {
  name: TTeam.TeamRole;
  description: string;
  permissions: string[];
  members: number;
}[] = [
  {
    name: 'owner',
    description: 'Полный доступ и биллинг.',
    permissions: ['Управление участниками', 'Биллинг', 'Все проекты', 'Журнал аудита'],
    members: 1,
  },
  {
    name: 'admin',
    description: 'Управление участниками и настройками.',
    permissions: ['Управление участниками', 'Все проекты', 'Журнал аудита'],
    members: 1,
  },
  {
    name: 'lead',
    description: 'Управление проектами и спринтами.',
    permissions: ['Создание проектов', 'Назначение задач', 'Просмотр отчётов'],
    members: 2,
  },
  {
    name: 'moderator',
    description: 'Модерация контента и сообщений.',
    permissions: ['Просмотр проектов', 'Управление задачами', 'Комментарии'],
    members: 1,
  },
  {
    name: 'member',
    description: 'Стандартный доступ участника команды.',
    permissions: ['Просмотр проектов', 'Управление задачами', 'Комментарии'],
    members: 3,
  },
  {
    name: 'viewer',
    description: 'Только просмотр проектов.',
    permissions: ['Просмотр проектов'],
    members: 1,
  },
];
