/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  ActionResponseOutput,
  GlobalErrorResponseOutput,
  PasswordResetConfirmDtoOutput,
  ResetPasswordDtoOutput,
  SignInDtoOutput,
  SignUpDtoOutput,
  VerifyDtoOutput,
  VerifyResetCodeDtoOutput,
} from '../../schemas';

import { instance } from '../../instance';
import type { ErrorType, BodyType } from '../../instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Создает пользователя, базовые настройки безопасности и уведомлений.
 * @summary Регистрация нового пользователя
 */
export const authControllerSignUp = (
  signUpDtoOutput: BodyType<SignUpDtoOutput>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    {
      url: `/api/v1/auth/sign-up`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signUpDtoOutput,
      signal,
    },
    options
  );
};

export const getAuthControllerSignUpMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignUp>>,
    TError,
    { data: BodyType<SignUpDtoOutput> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerSignUp>>,
  TError,
  { data: BodyType<SignUpDtoOutput> },
  TContext
> => {
  const mutationKey = ['authControllerSignUp'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerSignUp>>,
    { data: BodyType<SignUpDtoOutput> }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerSignUp(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerSignUpMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignUp>>
>;
export type AuthControllerSignUpMutationBody = BodyType<SignUpDtoOutput>;
export type AuthControllerSignUpMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Регистрация нового пользователя
 */
export const useAuthControllerSignUp = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerSignUp>>,
      TError,
      { data: BodyType<SignUpDtoOutput> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerSignUp>>,
  TError,
  { data: BodyType<SignUpDtoOutput> },
  TContext
> => {
  return useMutation(getAuthControllerSignUpMutationOptions(options), queryClient);
};
/**
 * Проверяет OTP из письма, создаёт аккаунт, выдаёт access-токен в теле ответа и устанавливает refresh в httpOnly cookie.
 * @summary Подтверждение регистрации по коду
 */
export const authControllerVerify = (
  verifyDtoOutput: BodyType<VerifyDtoOutput>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<unknown>(
    {
      url: `/api/v1/auth/sign-up/confirm`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: verifyDtoOutput,
      signal,
    },
    options
  );
};

export const getAuthControllerVerifyMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerVerify>>,
    TError,
    { data: BodyType<VerifyDtoOutput> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerVerify>>,
  TError,
  { data: BodyType<VerifyDtoOutput> },
  TContext
> => {
  const mutationKey = ['authControllerVerify'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerVerify>>,
    { data: BodyType<VerifyDtoOutput> }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerVerify(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerVerifyMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerVerify>>
>;
export type AuthControllerVerifyMutationBody = BodyType<VerifyDtoOutput>;
export type AuthControllerVerifyMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Подтверждение регистрации по коду
 */
export const useAuthControllerVerify = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerVerify>>,
      TError,
      { data: BodyType<VerifyDtoOutput> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerVerify>>,
  TError,
  { data: BodyType<VerifyDtoOutput> },
  TContext
> => {
  return useMutation(getAuthControllerVerifyMutationOptions(options), queryClient);
};
/**
 * Возвращает Access/Refresh токены. Если у пользователя включена 2FA, вернет временный токен.
 * @summary Вход в систему
 */
export const authControllerSignIn = (
  signInDtoOutput: BodyType<SignInDtoOutput>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<unknown>(
    {
      url: `/api/v1/auth/sign-in`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: signInDtoOutput,
      signal,
    },
    options
  );
};

export const getAuthControllerSignInMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignIn>>,
    TError,
    { data: BodyType<SignInDtoOutput> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerSignIn>>,
  TError,
  { data: BodyType<SignInDtoOutput> },
  TContext
> => {
  const mutationKey = ['authControllerSignIn'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerSignIn>>,
    { data: BodyType<SignInDtoOutput> }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerSignIn(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerSignInMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignIn>>
>;
export type AuthControllerSignInMutationBody = BodyType<SignInDtoOutput>;
export type AuthControllerSignInMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Вход в систему
 */
export const useAuthControllerSignIn = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerSignIn>>,
      TError,
      { data: BodyType<SignInDtoOutput> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerSignIn>>,
  TError,
  { data: BodyType<SignInDtoOutput> },
  TContext
> => {
  return useMutation(getAuthControllerSignInMutationOptions(options), queryClient);
};
/**
 * Удаляет текущую сессию пользователя из Redis.
 * @summary Выход из системы
 */
export const authControllerLogout = (
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    { url: `/api/v1/auth/sign-out`, method: 'POST', signal },
    options
  );
};

export const getAuthControllerLogoutMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['authControllerLogout'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLogout>>,
    void
  > = () => {
    return authControllerLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogout>>
>;

export type AuthControllerLogoutMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Выход из системы
 */
export const useAuthControllerLogout = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLogout>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof authControllerLogout>>, TError, void, TContext> => {
  return useMutation(getAuthControllerLogoutMutationOptions(options), queryClient);
};
/**
 * Выдает новую пару Access и Refresh токенов.
 * @summary Обновление токенов
 */
export const authControllerRefresh = (
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<unknown>({ url: `/api/v1/auth/refresh`, method: 'POST', signal }, options);
};

export const getAuthControllerRefreshMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRefresh>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRefresh>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['authControllerRefresh'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRefresh>>,
    void
  > = () => {
    return authControllerRefresh(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRefresh>>
>;

export type AuthControllerRefreshMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Обновление токенов
 */
export const useAuthControllerRefresh = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRefresh>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof authControllerRefresh>>, TError, void, TContext> => {
  return useMutation(getAuthControllerRefreshMutationOptions(options), queryClient);
};
/**
 * Отправляет одноразовый код на email, если пользователь существует.
 * @summary Запрос кода восстановления пароля
 */
export const authControllerResetPasswordRequest = (
  resetPasswordDtoOutput: BodyType<ResetPasswordDtoOutput>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    {
      url: `/api/v1/auth/password/reset`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: resetPasswordDtoOutput,
      signal,
    },
    options
  );
};

export const getAuthControllerResetPasswordRequestMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerResetPasswordRequest>>,
    TError,
    { data: BodyType<ResetPasswordDtoOutput> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerResetPasswordRequest>>,
  TError,
  { data: BodyType<ResetPasswordDtoOutput> },
  TContext
> => {
  const mutationKey = ['authControllerResetPasswordRequest'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerResetPasswordRequest>>,
    { data: BodyType<ResetPasswordDtoOutput> }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerResetPasswordRequest(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerResetPasswordRequestMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerResetPasswordRequest>>
>;
export type AuthControllerResetPasswordRequestMutationBody = BodyType<ResetPasswordDtoOutput>;
export type AuthControllerResetPasswordRequestMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Запрос кода восстановления пароля
 */
export const useAuthControllerResetPasswordRequest = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerResetPasswordRequest>>,
      TError,
      { data: BodyType<ResetPasswordDtoOutput> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerResetPasswordRequest>>,
  TError,
  { data: BodyType<ResetPasswordDtoOutput> },
  TContext
> => {
  return useMutation(getAuthControllerResetPasswordRequestMutationOptions(options), queryClient);
};
/**
 * Проверяет код из письма и помечает сессию сброса как подтверждённую.
 * @summary Проверка кода восстановления пароля
 */
export const authControllerVerifyResetCode = (
  verifyResetCodeDtoOutput: BodyType<VerifyResetCodeDtoOutput>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    {
      url: `/api/v1/auth/password/reset/verify`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: verifyResetCodeDtoOutput,
      signal,
    },
    options
  );
};

export const getAuthControllerVerifyResetCodeMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerVerifyResetCode>>,
    TError,
    { data: BodyType<VerifyResetCodeDtoOutput> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerVerifyResetCode>>,
  TError,
  { data: BodyType<VerifyResetCodeDtoOutput> },
  TContext
> => {
  const mutationKey = ['authControllerVerifyResetCode'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerVerifyResetCode>>,
    { data: BodyType<VerifyResetCodeDtoOutput> }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerVerifyResetCode(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerVerifyResetCodeMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerVerifyResetCode>>
>;
export type AuthControllerVerifyResetCodeMutationBody = BodyType<VerifyResetCodeDtoOutput>;
export type AuthControllerVerifyResetCodeMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Проверка кода восстановления пароля
 */
export const useAuthControllerVerifyResetCode = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerVerifyResetCode>>,
      TError,
      { data: BodyType<VerifyResetCodeDtoOutput> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerVerifyResetCode>>,
  TError,
  { data: BodyType<VerifyResetCodeDtoOutput> },
  TContext
> => {
  return useMutation(getAuthControllerVerifyResetCodeMutationOptions(options), queryClient);
};
/**
 * Доступно только после успешной проверки кода на шаге verify.
 * @summary Установка нового пароля после сброса
 */
export const authControllerConfirmPasswordReset = (
  passwordResetConfirmDtoOutput: BodyType<PasswordResetConfirmDtoOutput>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    {
      url: `/api/v1/auth/password/reset/confirm`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: passwordResetConfirmDtoOutput,
      signal,
    },
    options
  );
};

export const getAuthControllerConfirmPasswordResetMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerConfirmPasswordReset>>,
    TError,
    { data: BodyType<PasswordResetConfirmDtoOutput> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerConfirmPasswordReset>>,
  TError,
  { data: BodyType<PasswordResetConfirmDtoOutput> },
  TContext
> => {
  const mutationKey = ['authControllerConfirmPasswordReset'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerConfirmPasswordReset>>,
    { data: BodyType<PasswordResetConfirmDtoOutput> }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerConfirmPasswordReset(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerConfirmPasswordResetMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerConfirmPasswordReset>>
>;
export type AuthControllerConfirmPasswordResetMutationBody =
  BodyType<PasswordResetConfirmDtoOutput>;
export type AuthControllerConfirmPasswordResetMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Установка нового пароля после сброса
 */
export const useAuthControllerConfirmPasswordReset = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerConfirmPasswordReset>>,
      TError,
      { data: BodyType<PasswordResetConfirmDtoOutput> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerConfirmPasswordReset>>,
  TError,
  { data: BodyType<PasswordResetConfirmDtoOutput> },
  TContext
> => {
  return useMutation(getAuthControllerConfirmPasswordResetMutationOptions(options), queryClient);
};
