/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ActionResponseOutput,
  CheckSlugResponseOutput,
  CreateTeamDtoOutput,
  FileUploadResponseOutput,
  GlobalErrorResponseOutput,
  InviteMemberDtoOutput,
  SyncTagsDtoOutput,
  TeamMemberResponseOutput,
  TeamsControllerFindOne200,
  TeamsControllerUpdateTeamAvatarBody,
  TeamsControllerUpdateTeamBannerBody,
  UpdateMemberDtoOutput,
  UpdateTeamDtoOutput,
  UserInviteResponseOutput,
  UserTeamResponseOutput,
} from '../../schemas';

import { instance } from '../../instance';
import type { ErrorType, BodyType } from '../../instance';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Создать новую команду
 */
export const teamsControllerCreate = (
  createTeamDtoOutput: BodyType<CreateTeamDtoOutput>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    {
      url: `/api/v1/teams`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTeamDtoOutput,
      signal,
    },
    options
  );
};

export const getTeamsControllerCreateMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsControllerCreate>>,
    TError,
    { data: BodyType<CreateTeamDtoOutput> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsControllerCreate>>,
  TError,
  { data: BodyType<CreateTeamDtoOutput> },
  TContext
> => {
  const mutationKey = ['teamsControllerCreate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsControllerCreate>>,
    { data: BodyType<CreateTeamDtoOutput> }
  > = (props) => {
    const { data } = props ?? {};

    return teamsControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsControllerCreate>>
>;
export type TeamsControllerCreateMutationBody = BodyType<CreateTeamDtoOutput>;
export type TeamsControllerCreateMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Создать новую команду
 */
export const useTeamsControllerCreate = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof teamsControllerCreate>>,
      TError,
      { data: BodyType<CreateTeamDtoOutput> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof teamsControllerCreate>>,
  TError,
  { data: BodyType<CreateTeamDtoOutput> },
  TContext
> => {
  return useMutation(getTeamsControllerCreateMutationOptions(options), queryClient);
};
/**
 * Проверяет, свободен ли уникальный адрес команды для использования.
 * @summary Проверить доступность слага
 */
export const teamsControllerCheckSlug = (
  slug: string,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<CheckSlugResponseOutput>(
    { url: `/api/v1/teams/check-slug/${slug}`, method: 'GET', signal },
    options
  );
};

export const getTeamsControllerCheckSlugQueryKey = (slug: string) => {
  return [`/api/v1/teams/check-slug/${slug}`] as const;
};

export const getTeamsControllerCheckSlugQueryOptions = <
  TData = Awaited<ReturnType<typeof teamsControllerCheckSlug>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerCheckSlug>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTeamsControllerCheckSlugQueryKey(slug);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof teamsControllerCheckSlug>>> = ({
    signal,
  }) => teamsControllerCheckSlug(slug, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!slug, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof teamsControllerCheckSlug>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TeamsControllerCheckSlugQueryResult = NonNullable<
  Awaited<ReturnType<typeof teamsControllerCheckSlug>>
>;
export type TeamsControllerCheckSlugQueryError = ErrorType<GlobalErrorResponseOutput>;

export function useTeamsControllerCheckSlug<
  TData = Awaited<ReturnType<typeof teamsControllerCheckSlug>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerCheckSlug>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamsControllerCheckSlug>>,
          TError,
          Awaited<ReturnType<typeof teamsControllerCheckSlug>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTeamsControllerCheckSlug<
  TData = Awaited<ReturnType<typeof teamsControllerCheckSlug>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerCheckSlug>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamsControllerCheckSlug>>,
          TError,
          Awaited<ReturnType<typeof teamsControllerCheckSlug>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTeamsControllerCheckSlug<
  TData = Awaited<ReturnType<typeof teamsControllerCheckSlug>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerCheckSlug>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Проверить доступность слага
 */

export function useTeamsControllerCheckSlug<
  TData = Awaited<ReturnType<typeof teamsControllerCheckSlug>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerCheckSlug>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTeamsControllerCheckSlugQueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Возвращает все команды, в которых текущий пользователь является участником или владельцем.
 * @summary Получить список команд пользователя
 */
export const teamsControllerFindAll = (
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<UserTeamResponseOutput[]>(
    { url: `/api/v1/teams/my`, method: 'GET', signal },
    options
  );
};

export const getTeamsControllerFindAllQueryKey = () => {
  return [`/api/v1/teams/my`] as const;
};

export const getTeamsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof teamsControllerFindAll>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindAll>>, TError, TData>
  >;
  request?: SecondParameter<typeof instance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTeamsControllerFindAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof teamsControllerFindAll>>> = ({ signal }) =>
    teamsControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof teamsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TeamsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof teamsControllerFindAll>>
>;
export type TeamsControllerFindAllQueryError = ErrorType<GlobalErrorResponseOutput>;

export function useTeamsControllerFindAll<
  TData = Awaited<ReturnType<typeof teamsControllerFindAll>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof teamsControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTeamsControllerFindAll<
  TData = Awaited<ReturnType<typeof teamsControllerFindAll>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof teamsControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTeamsControllerFindAll<
  TData = Awaited<ReturnType<typeof teamsControllerFindAll>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить список команд пользователя
 */

export function useTeamsControllerFindAll<
  TData = Awaited<ReturnType<typeof teamsControllerFindAll>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTeamsControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Возвращает все активные приглашения в команды, отправленные на email текущего пользователя.
 * @summary Получить список входящих приглашений
 */
export const teamsControllerFindAllInvites = (
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<UserInviteResponseOutput[]>(
    { url: `/api/v1/teams/my/invites`, method: 'GET', signal },
    options
  );
};

export const getTeamsControllerFindAllInvitesQueryKey = () => {
  return [`/api/v1/teams/my/invites`] as const;
};

export const getTeamsControllerFindAllInvitesQueryOptions = <
  TData = Awaited<ReturnType<typeof teamsControllerFindAllInvites>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindAllInvites>>, TError, TData>
  >;
  request?: SecondParameter<typeof instance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTeamsControllerFindAllInvitesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof teamsControllerFindAllInvites>>> = ({
    signal,
  }) => teamsControllerFindAllInvites(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof teamsControllerFindAllInvites>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TeamsControllerFindAllInvitesQueryResult = NonNullable<
  Awaited<ReturnType<typeof teamsControllerFindAllInvites>>
>;
export type TeamsControllerFindAllInvitesQueryError = ErrorType<GlobalErrorResponseOutput>;

export function useTeamsControllerFindAllInvites<
  TData = Awaited<ReturnType<typeof teamsControllerFindAllInvites>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindAllInvites>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamsControllerFindAllInvites>>,
          TError,
          Awaited<ReturnType<typeof teamsControllerFindAllInvites>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTeamsControllerFindAllInvites<
  TData = Awaited<ReturnType<typeof teamsControllerFindAllInvites>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindAllInvites>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamsControllerFindAllInvites>>,
          TError,
          Awaited<ReturnType<typeof teamsControllerFindAllInvites>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTeamsControllerFindAllInvites<
  TData = Awaited<ReturnType<typeof teamsControllerFindAllInvites>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindAllInvites>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить список входящих приглашений
 */

export function useTeamsControllerFindAllInvites<
  TData = Awaited<ReturnType<typeof teamsControllerFindAllInvites>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindAllInvites>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTeamsControllerFindAllInvitesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Получить детальную информацию о команде по slug
 */
export const teamsControllerFindOne = (
  slug: string,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<TeamsControllerFindOne200>(
    { url: `/api/v1/teams/${slug}`, method: 'GET', signal },
    options
  );
};

export const getTeamsControllerFindOneQueryKey = (slug: string) => {
  return [`/api/v1/teams/${slug}`] as const;
};

export const getTeamsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof teamsControllerFindOne>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTeamsControllerFindOneQueryKey(slug);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof teamsControllerFindOne>>> = ({ signal }) =>
    teamsControllerFindOne(slug, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!slug, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof teamsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TeamsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof teamsControllerFindOne>>
>;
export type TeamsControllerFindOneQueryError = ErrorType<GlobalErrorResponseOutput>;

export function useTeamsControllerFindOne<
  TData = Awaited<ReturnType<typeof teamsControllerFindOne>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof teamsControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTeamsControllerFindOne<
  TData = Awaited<ReturnType<typeof teamsControllerFindOne>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof teamsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof teamsControllerFindOne>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTeamsControllerFindOne<
  TData = Awaited<ReturnType<typeof teamsControllerFindOne>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить детальную информацию о команде по slug
 */

export function useTeamsControllerFindOne<
  TData = Awaited<ReturnType<typeof teamsControllerFindOne>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof teamsControllerFindOne>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTeamsControllerFindOneQueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Обновить данные команды
 */
export const teamsControllerUpdate = (
  slug: string,
  updateTeamDtoOutput: BodyType<UpdateTeamDtoOutput>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    {
      url: `/api/v1/teams/${slug}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateTeamDtoOutput,
      signal,
    },
    options
  );
};

export const getTeamsControllerUpdateMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsControllerUpdate>>,
    TError,
    { slug: string; data: BodyType<UpdateTeamDtoOutput> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsControllerUpdate>>,
  TError,
  { slug: string; data: BodyType<UpdateTeamDtoOutput> },
  TContext
> => {
  const mutationKey = ['teamsControllerUpdate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsControllerUpdate>>,
    { slug: string; data: BodyType<UpdateTeamDtoOutput> }
  > = (props) => {
    const { slug, data } = props ?? {};

    return teamsControllerUpdate(slug, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsControllerUpdate>>
>;
export type TeamsControllerUpdateMutationBody = BodyType<UpdateTeamDtoOutput>;
export type TeamsControllerUpdateMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Обновить данные команды
 */
export const useTeamsControllerUpdate = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof teamsControllerUpdate>>,
      TError,
      { slug: string; data: BodyType<UpdateTeamDtoOutput> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof teamsControllerUpdate>>,
  TError,
  { slug: string; data: BodyType<UpdateTeamDtoOutput> },
  TContext
> => {
  return useMutation(getTeamsControllerUpdateMutationOptions(options), queryClient);
};
/**
 * @summary Удалить команду
 */
export const teamsControllerRemove = (
  slug: string,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    { url: `/api/v1/teams/${slug}`, method: 'DELETE', signal },
    options
  );
};

export const getTeamsControllerRemoveMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsControllerRemove>>,
    TError,
    { slug: string },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsControllerRemove>>,
  TError,
  { slug: string },
  TContext
> => {
  const mutationKey = ['teamsControllerRemove'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsControllerRemove>>,
    { slug: string }
  > = (props) => {
    const { slug } = props ?? {};

    return teamsControllerRemove(slug, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsControllerRemove>>
>;

export type TeamsControllerRemoveMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Удалить команду
 */
export const useTeamsControllerRemove = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof teamsControllerRemove>>,
      TError,
      { slug: string },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof teamsControllerRemove>>,
  TError,
  { slug: string },
  TContext
> => {
  return useMutation(getTeamsControllerRemoveMutationOptions(options), queryClient);
};
/**
 * @summary Синхронизировать теги команды
 */
export const teamsControllerSyncTags = (
  slug: string,
  syncTagsDtoOutput: BodyType<SyncTagsDtoOutput>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    {
      url: `/api/v1/teams/${slug}/tags`,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      data: syncTagsDtoOutput,
      signal,
    },
    options
  );
};

export const getTeamsControllerSyncTagsMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsControllerSyncTags>>,
    TError,
    { slug: string; data: BodyType<SyncTagsDtoOutput> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsControllerSyncTags>>,
  TError,
  { slug: string; data: BodyType<SyncTagsDtoOutput> },
  TContext
> => {
  const mutationKey = ['teamsControllerSyncTags'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsControllerSyncTags>>,
    { slug: string; data: BodyType<SyncTagsDtoOutput> }
  > = (props) => {
    const { slug, data } = props ?? {};

    return teamsControllerSyncTags(slug, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsControllerSyncTagsMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsControllerSyncTags>>
>;
export type TeamsControllerSyncTagsMutationBody = BodyType<SyncTagsDtoOutput>;
export type TeamsControllerSyncTagsMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Синхронизировать теги команды
 */
export const useTeamsControllerSyncTags = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof teamsControllerSyncTags>>,
      TError,
      { slug: string; data: BodyType<SyncTagsDtoOutput> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof teamsControllerSyncTags>>,
  TError,
  { slug: string; data: BodyType<SyncTagsDtoOutput> },
  TContext
> => {
  return useMutation(getTeamsControllerSyncTagsMutationOptions(options), queryClient);
};
/**
 * Загрузка файла изображения для профиля команды.
 * @summary Обновить аватар команды
 */
export const teamsControllerUpdateTeamAvatar = (
  slug: string,
  teamsControllerUpdateTeamAvatarBody: BodyType<TeamsControllerUpdateTeamAvatarBody>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  const formData = new FormData();
  if (teamsControllerUpdateTeamAvatarBody.file !== undefined) {
    formData.append(`file`, teamsControllerUpdateTeamAvatarBody.file);
  }

  return instance<FileUploadResponseOutput>(
    { url: `/api/v1/teams/${slug}/avatar`, method: 'PATCH', data: formData, signal },
    options
  );
};

export const getTeamsControllerUpdateTeamAvatarMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsControllerUpdateTeamAvatar>>,
    TError,
    { slug: string; data: BodyType<TeamsControllerUpdateTeamAvatarBody> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsControllerUpdateTeamAvatar>>,
  TError,
  { slug: string; data: BodyType<TeamsControllerUpdateTeamAvatarBody> },
  TContext
> => {
  const mutationKey = ['teamsControllerUpdateTeamAvatar'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsControllerUpdateTeamAvatar>>,
    { slug: string; data: BodyType<TeamsControllerUpdateTeamAvatarBody> }
  > = (props) => {
    const { slug, data } = props ?? {};

    return teamsControllerUpdateTeamAvatar(slug, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsControllerUpdateTeamAvatarMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsControllerUpdateTeamAvatar>>
>;
export type TeamsControllerUpdateTeamAvatarMutationBody =
  BodyType<TeamsControllerUpdateTeamAvatarBody>;
export type TeamsControllerUpdateTeamAvatarMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Обновить аватар команды
 */
export const useTeamsControllerUpdateTeamAvatar = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof teamsControllerUpdateTeamAvatar>>,
      TError,
      { slug: string; data: BodyType<TeamsControllerUpdateTeamAvatarBody> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof teamsControllerUpdateTeamAvatar>>,
  TError,
  { slug: string; data: BodyType<TeamsControllerUpdateTeamAvatarBody> },
  TContext
> => {
  return useMutation(getTeamsControllerUpdateTeamAvatarMutationOptions(options), queryClient);
};
/**
 * Загрузка файла изображения для обложки (баннера) команды.
 * @summary Обновить баннер команды
 */
export const teamsControllerUpdateTeamBanner = (
  slug: string,
  teamsControllerUpdateTeamBannerBody: BodyType<TeamsControllerUpdateTeamBannerBody>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  const formData = new FormData();
  if (teamsControllerUpdateTeamBannerBody.file !== undefined) {
    formData.append(`file`, teamsControllerUpdateTeamBannerBody.file);
  }

  return instance<FileUploadResponseOutput>(
    { url: `/api/v1/teams/${slug}/banner`, method: 'PATCH', data: formData, signal },
    options
  );
};

export const getTeamsControllerUpdateTeamBannerMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof teamsControllerUpdateTeamBanner>>,
    TError,
    { slug: string; data: BodyType<TeamsControllerUpdateTeamBannerBody> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof teamsControllerUpdateTeamBanner>>,
  TError,
  { slug: string; data: BodyType<TeamsControllerUpdateTeamBannerBody> },
  TContext
> => {
  const mutationKey = ['teamsControllerUpdateTeamBanner'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof teamsControllerUpdateTeamBanner>>,
    { slug: string; data: BodyType<TeamsControllerUpdateTeamBannerBody> }
  > = (props) => {
    const { slug, data } = props ?? {};

    return teamsControllerUpdateTeamBanner(slug, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TeamsControllerUpdateTeamBannerMutationResult = NonNullable<
  Awaited<ReturnType<typeof teamsControllerUpdateTeamBanner>>
>;
export type TeamsControllerUpdateTeamBannerMutationBody =
  BodyType<TeamsControllerUpdateTeamBannerBody>;
export type TeamsControllerUpdateTeamBannerMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Обновить баннер команды
 */
export const useTeamsControllerUpdateTeamBanner = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof teamsControllerUpdateTeamBanner>>,
      TError,
      { slug: string; data: BodyType<TeamsControllerUpdateTeamBannerBody> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof teamsControllerUpdateTeamBanner>>,
  TError,
  { slug: string; data: BodyType<TeamsControllerUpdateTeamBannerBody> },
  TContext
> => {
  return useMutation(getTeamsControllerUpdateTeamBannerMutationOptions(options), queryClient);
};
/**
 * @summary Получить список всех участников команды
 */
export const membersControllerGetMembers = (
  slug: string,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<TeamMemberResponseOutput[]>(
    { url: `/api/v1/teams/${slug}/members`, method: 'GET', signal },
    options
  );
};

export const getMembersControllerGetMembersQueryKey = (slug: string) => {
  return [`/api/v1/teams/${slug}/members`] as const;
};

export const getMembersControllerGetMembersQueryOptions = <
  TData = Awaited<ReturnType<typeof membersControllerGetMembers>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof membersControllerGetMembers>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMembersControllerGetMembersQueryKey(slug);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof membersControllerGetMembers>>> = ({
    signal,
  }) => membersControllerGetMembers(slug, requestOptions, signal);

  return { queryKey, queryFn, enabled: !!slug, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof membersControllerGetMembers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MembersControllerGetMembersQueryResult = NonNullable<
  Awaited<ReturnType<typeof membersControllerGetMembers>>
>;
export type MembersControllerGetMembersQueryError = ErrorType<GlobalErrorResponseOutput>;

export function useMembersControllerGetMembers<
  TData = Awaited<ReturnType<typeof membersControllerGetMembers>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof membersControllerGetMembers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof membersControllerGetMembers>>,
          TError,
          Awaited<ReturnType<typeof membersControllerGetMembers>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMembersControllerGetMembers<
  TData = Awaited<ReturnType<typeof membersControllerGetMembers>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof membersControllerGetMembers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof membersControllerGetMembers>>,
          TError,
          Awaited<ReturnType<typeof membersControllerGetMembers>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMembersControllerGetMembers<
  TData = Awaited<ReturnType<typeof membersControllerGetMembers>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof membersControllerGetMembers>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Получить список всех участников команды
 */

export function useMembersControllerGetMembers<
  TData = Awaited<ReturnType<typeof membersControllerGetMembers>>,
  TError = ErrorType<GlobalErrorResponseOutput>,
>(
  slug: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof membersControllerGetMembers>>, TError, TData>
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMembersControllerGetMembersQueryOptions(slug, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Создает запись об участнике со статусом "pending". Если пользователь уже зарегистрирован — он увидит приглашение в разделе "my/invites". Если нет — ему уйдет письмо на указанный Email.
 * @summary Пригласить пользователя в команду по Email
 */
export const membersControllerInvite = (
  slug: string,
  inviteMemberDtoOutput: BodyType<InviteMemberDtoOutput>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    {
      url: `/api/v1/teams/${slug}/invitations`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: inviteMemberDtoOutput,
      signal,
    },
    options
  );
};

export const getMembersControllerInviteMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof membersControllerInvite>>,
    TError,
    { slug: string; data: BodyType<InviteMemberDtoOutput> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof membersControllerInvite>>,
  TError,
  { slug: string; data: BodyType<InviteMemberDtoOutput> },
  TContext
> => {
  const mutationKey = ['membersControllerInvite'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof membersControllerInvite>>,
    { slug: string; data: BodyType<InviteMemberDtoOutput> }
  > = (props) => {
    const { slug, data } = props ?? {};

    return membersControllerInvite(slug, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MembersControllerInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof membersControllerInvite>>
>;
export type MembersControllerInviteMutationBody = BodyType<InviteMemberDtoOutput>;
export type MembersControllerInviteMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Пригласить пользователя в команду по Email
 */
export const useMembersControllerInvite = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof membersControllerInvite>>,
      TError,
      { slug: string; data: BodyType<InviteMemberDtoOutput> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof membersControllerInvite>>,
  TError,
  { slug: string; data: BodyType<InviteMemberDtoOutput> },
  TContext
> => {
  return useMutation(getMembersControllerInviteMutationOptions(options), queryClient);
};
/**
 * Активирует участие пользователя в команде по уникальному коду приглашения. После успешного принятия статус участника меняется с "pending" на "active". Система автоматически связывает текущего авторизованного пользователя с инвайтом через Email.
 * @summary Принять приглашение в команду
 */
export const membersControllerAccept = (
  slug: string,
  code: string,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    { url: `/api/v1/teams/${slug}/invitations/${code}/accept`, method: 'POST', signal },
    options
  );
};

export const getMembersControllerAcceptMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof membersControllerAccept>>,
    TError,
    { slug: string; code: string },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof membersControllerAccept>>,
  TError,
  { slug: string; code: string },
  TContext
> => {
  const mutationKey = ['membersControllerAccept'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof membersControllerAccept>>,
    { slug: string; code: string }
  > = (props) => {
    const { slug, code } = props ?? {};

    return membersControllerAccept(slug, code, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MembersControllerAcceptMutationResult = NonNullable<
  Awaited<ReturnType<typeof membersControllerAccept>>
>;

export type MembersControllerAcceptMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Принять приглашение в команду
 */
export const useMembersControllerAccept = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof membersControllerAccept>>,
      TError,
      { slug: string; code: string },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof membersControllerAccept>>,
  TError,
  { slug: string; code: string },
  TContext
> => {
  return useMutation(getMembersControllerAcceptMutationOptions(options), queryClient);
};
/**
 * Позволяет изменить роль участника (member -> admin) или вручную изменить его статус. Владелец команды (Owner) не может понизить свою роль через этот эндпоинт.
 * @summary Изменить роль или статус участника
 */
export const membersControllerUpdateMember = (
  slug: string,
  userId: string,
  updateMemberDtoOutput: BodyType<UpdateMemberDtoOutput>,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    {
      url: `/api/v1/teams/${slug}/members/${userId}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateMemberDtoOutput,
      signal,
    },
    options
  );
};

export const getMembersControllerUpdateMemberMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof membersControllerUpdateMember>>,
    TError,
    { slug: string; userId: string; data: BodyType<UpdateMemberDtoOutput> },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof membersControllerUpdateMember>>,
  TError,
  { slug: string; userId: string; data: BodyType<UpdateMemberDtoOutput> },
  TContext
> => {
  const mutationKey = ['membersControllerUpdateMember'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof membersControllerUpdateMember>>,
    { slug: string; userId: string; data: BodyType<UpdateMemberDtoOutput> }
  > = (props) => {
    const { slug, userId, data } = props ?? {};

    return membersControllerUpdateMember(slug, userId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MembersControllerUpdateMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof membersControllerUpdateMember>>
>;
export type MembersControllerUpdateMemberMutationBody = BodyType<UpdateMemberDtoOutput>;
export type MembersControllerUpdateMemberMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Изменить роль или статус участника
 */
export const useMembersControllerUpdateMember = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof membersControllerUpdateMember>>,
      TError,
      { slug: string; userId: string; data: BodyType<UpdateMemberDtoOutput> },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof membersControllerUpdateMember>>,
  TError,
  { slug: string; userId: string; data: BodyType<UpdateMemberDtoOutput> },
  TContext
> => {
  return useMutation(getMembersControllerUpdateMemberMutationOptions(options), queryClient);
};
/**
 * @summary Удалить участника из команды
 */
export const membersControllerRemoveMember = (
  slug: string,
  userId: string,
  options?: SecondParameter<typeof instance>,
  signal?: AbortSignal
) => {
  return instance<ActionResponseOutput>(
    { url: `/api/v1/teams/${slug}/members/${userId}`, method: 'DELETE', signal },
    options
  );
};

export const getMembersControllerRemoveMemberMutationOptions = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof membersControllerRemoveMember>>,
    TError,
    { slug: string; userId: string },
    TContext
  >;
  request?: SecondParameter<typeof instance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof membersControllerRemoveMember>>,
  TError,
  { slug: string; userId: string },
  TContext
> => {
  const mutationKey = ['membersControllerRemoveMember'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof membersControllerRemoveMember>>,
    { slug: string; userId: string }
  > = (props) => {
    const { slug, userId } = props ?? {};

    return membersControllerRemoveMember(slug, userId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MembersControllerRemoveMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof membersControllerRemoveMember>>
>;

export type MembersControllerRemoveMemberMutationError = ErrorType<GlobalErrorResponseOutput>;

/**
 * @summary Удалить участника из команды
 */
export const useMembersControllerRemoveMember = <
  TError = ErrorType<GlobalErrorResponseOutput>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof membersControllerRemoveMember>>,
      TError,
      { slug: string; userId: string },
      TContext
    >;
    request?: SecondParameter<typeof instance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof membersControllerRemoveMember>>,
  TError,
  { slug: string; userId: string },
  TContext
> => {
  return useMutation(getMembersControllerRemoveMemberMutationOptions(options), queryClient);
};
