/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */

export interface ActionResponseOutput {
  /** Статус операции */
  success: boolean;
  /** Сообщение для пользователя */
  message?: string;
}
