/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const ActionResponseOutput = zod.object({
  success: zod.boolean().describe('Статус операции'),
  message: zod.string().optional().describe('Сообщение для пользователя'),
});

export type ActionResponseOutput = zod.input<typeof ActionResponseOutput>;
export type ActionResponseOutputOutput = zod.output<typeof ActionResponseOutput>;
