/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const authControllerResetPasswordRequestBodyEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$"
);

export const AuthControllerResetPasswordRequestBody = zod.object({
  email: zod
    .email()
    .regex(authControllerResetPasswordRequestBodyEmailRegExp)
    .describe('Email для восстановления'),
});

export type AuthControllerResetPasswordRequestBody = zod.input<
  typeof AuthControllerResetPasswordRequestBody
>;
export type AuthControllerResetPasswordRequestBodyOutput = zod.output<
  typeof AuthControllerResetPasswordRequestBody
>;
