/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const authControllerVerifyBodyEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$"
);
export const authControllerVerifyBodyCodeMin = 6;
export const authControllerVerifyBodyCodeMax = 6;

export const AuthControllerVerifyBody = zod
  .object({
    email: zod
      .email()
      .regex(authControllerVerifyBodyEmailRegExp)
      .describe('Email пользователя, на который был отправлен код'),
    code: zod
      .string()
      .min(authControllerVerifyBodyCodeMin)
      .max(authControllerVerifyBodyCodeMax)
      .describe('6-значный OTP код подтверждения'),
  })
  .describe('Схема верификации OTP кода');

export type AuthControllerVerifyBody = zod.input<typeof AuthControllerVerifyBody>;
export type AuthControllerVerifyBodyOutput = zod.output<typeof AuthControllerVerifyBody>;
