/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const authControllerSignUpBodyEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$"
);
export const authControllerSignUpBodyPasswordMin = 8;
export const authControllerSignUpBodyPasswordMax = 32;

export const authControllerSignUpBodyFirstNameMin = 2;
export const authControllerSignUpBodyFirstNameMax = 50;

export const authControllerSignUpBodyLastNameMin = 2;
export const authControllerSignUpBodyLastNameMax = 50;

export const authControllerSignUpBodyMiddleNameOneMax = 50;

export const AuthControllerSignUpBody = zod
  .object({
    email: zod.email().regex(authControllerSignUpBodyEmailRegExp).describe('Email пользователя'),
    password: zod
      .string()
      .min(authControllerSignUpBodyPasswordMin)
      .max(authControllerSignUpBodyPasswordMax)
      .describe('Пароль (минимум 8 символов)'),
    firstName: zod
      .string()
      .min(authControllerSignUpBodyFirstNameMin)
      .max(authControllerSignUpBodyFirstNameMax)
      .describe('Имя'),
    lastName: zod
      .string()
      .min(authControllerSignUpBodyLastNameMin)
      .max(authControllerSignUpBodyLastNameMax)
      .describe('Фамилия'),
    middleName: zod
      .union([zod.string().max(authControllerSignUpBodyMiddleNameOneMax), zod.enum([''])])
      .optional()
      .describe('Отчество (опционально)'),
  })
  .describe('Схема регистрации пользователя');

export type AuthControllerSignUpBody = zod.input<typeof AuthControllerSignUpBody>;
export type AuthControllerSignUpBodyOutput = zod.output<typeof AuthControllerSignUpBody>;
