/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const authControllerVerifyResetCodeBodyEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$"
);
export const authControllerVerifyResetCodeBodyCodeMin = 6;
export const authControllerVerifyResetCodeBodyCodeMax = 6;

export const AuthControllerVerifyResetCodeBody = zod.object({
  email: zod.email().regex(authControllerVerifyResetCodeBodyEmailRegExp),
  code: zod
    .string()
    .min(authControllerVerifyResetCodeBodyCodeMin)
    .max(authControllerVerifyResetCodeBodyCodeMax)
    .describe('Код из письма'),
});

export type AuthControllerVerifyResetCodeBody = zod.input<typeof AuthControllerVerifyResetCodeBody>;
export type AuthControllerVerifyResetCodeBodyOutput = zod.output<
  typeof AuthControllerVerifyResetCodeBody
>;
