/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const authControllerConfirmPasswordResetBodyEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$"
);
export const authControllerConfirmPasswordResetBodyPasswordMin = 8;
export const authControllerConfirmPasswordResetBodyPasswordMax = 32;

export const AuthControllerConfirmPasswordResetBody = zod.object({
  email: zod.email().regex(authControllerConfirmPasswordResetBodyEmailRegExp),
  password: zod
    .string()
    .min(authControllerConfirmPasswordResetBodyPasswordMin)
    .max(authControllerConfirmPasswordResetBodyPasswordMax)
    .describe('Новый пароль'),
  confirmPassword: zod.string().describe('Повторите новый пароль'),
});

export type AuthControllerConfirmPasswordResetBody = zod.input<
  typeof AuthControllerConfirmPasswordResetBody
>;
export type AuthControllerConfirmPasswordResetBodyOutput = zod.output<
  typeof AuthControllerConfirmPasswordResetBody
>;
