/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const CheckSlugResponseOutput = zod.object({
  available: zod
    .boolean()
    .describe('Флаг доступности: true — адрес свободен, false — уже занят или некорректен'),
});

export type CheckSlugResponseOutput = zod.input<typeof CheckSlugResponseOutput>;
export type CheckSlugResponseOutputOutput = zod.output<typeof CheckSlugResponseOutput>;
