/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const createTeamDtoOutputNameMin = 2;
export const createTeamDtoOutputNameMax = 100;

export const createTeamDtoOutputDescriptionMax = 500;

export const CreateTeamDtoOutput = zod.object({
  name: zod
    .string()
    .min(createTeamDtoOutputNameMin)
    .max(createTeamDtoOutputNameMax)
    .describe('Название команды, отображаемое в интерфейсе'),
  description: zod
    .string()
    .max(createTeamDtoOutputDescriptionMax)
    .optional()
    .describe('Краткое описание деятельнос��и или целей команды'),
  slug: zod.string().optional().describe('Уникальная ссылка на изображение команду'),
  tags: zod
    .array(zod.string())
    .optional()
    .describe('Список строковых названий тегов для классификации'),
});

export type CreateTeamDtoOutput = zod.input<typeof CreateTeamDtoOutput>;
export type CreateTeamDtoOutputOutput = zod.output<typeof CreateTeamDtoOutput>;
