/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const FileUploadResponseOutput = zod.object({
  success: zod.boolean().describe('Статус операции'),
  url: zod.string().describe('URL загруженного файла'),
  message: zod.string().optional().describe('Сообщение для пользователя'),
});

export type FileUploadResponseOutput = zod.input<typeof FileUploadResponseOutput>;
export type FileUploadResponseOutputOutput = zod.output<typeof FileUploadResponseOutput>;
