/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import type { GlobalErrorResponseOutputDetailsItem } from './globalErrorResponseOutputDetailsItem';
import type { GlobalErrorResponseOutputMeta } from './globalErrorResponseOutputMeta';

export interface GlobalErrorResponseOutput {
  /** Уникальный бизнес-код ошибки (например, "INSUFFICIENT_FUNDS", "TEAM_NOT_FOUND") */
  code: string;
  /** Краткое описание ошибки для пользователя или разработчика */
  message: string;
  /** Флаг, указывающий клиенту, есть ли смысл повторять запрос без изменений (например, при 503 или Lock Timeout) */
  retryable: boolean;
  /** Список ошибок валидации (заполняется только для 400 ошибок) */
  details?: GlobalErrorResponseOutputDetailsItem[];
  /** Техническая мета-информация для мониторинга и отладки */
  meta: GlobalErrorResponseOutputMeta;
}
