/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const globalErrorResponseOutputOneMetaTimestampRegExp = new RegExp(
  '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
);

export const GlobalErrorResponseOutput = zod.object({
  code: zod
    .string()
    .describe(
      'Уникальный бизнес-код ошибки (например, \"INSUFFICIENT_FUNDS\", \"TEAM_NOT_FOUND\")'
    ),
  message: zod.string().describe('Краткое описание ошибки для пользователя или разработчика'),
  retryable: zod
    .boolean()
    .describe(
      'Флаг, указывающий клиенту, есть ли смысл повторять запрос без изменений (например, при 503 или Lock Timeout)'
    ),
  details: zod
    .array(
      zod
        .object({
          field: zod
            .string()
            .describe('Путь к полю в формате dot-notation (например, \"user.email\")'),
          message: zod
            .string()
            .describe('Человекочитаемое сообщение о конкретной ошибке в этом поле'),
          code: zod
            .string()
            .describe(
              'Машиночитаемый код ошибки валидации (например, \"invalid_email\", \"too_short\")'
            ),
        })
        .describe('Детальная информация о конкретном нарушении в запросе')
    )
    .optional()
    .describe('Список ошибок валидации (заполняется только для 400 ошибок)'),
  meta: zod
    .object({
      requestId: zod
        .string()
        .describe(
          'Уникальный ID запроса (Trace ID). Используется для поиска логов в Sentry\/ELK\/Kibana'
        ),
      timestamp: zod.iso
        .datetime({})
        .regex(globalErrorResponseOutputOneMetaTimestampRegExp)
        .describe('Точное время возникновения ошибки в формате ISO 8601'),
      path: zod.string().describe('URL-путь эндпоинта, который вернул ошибку'),
      method: zod.string().describe('HTTP метод запроса (GET, POST, etc.)'),
      service: zod
        .string()
        .optional()
        .describe(
          'Имя микросервиса, в котором произошел сбой (полезно для будущего масштабирования)'
        ),
    })
    .describe('Техническая мета-информация для мониторинга и отладки'),
});

export type GlobalErrorResponseOutput = zod.input<typeof GlobalErrorResponseOutput>;
export type GlobalErrorResponseOutputOutput = zod.output<typeof GlobalErrorResponseOutput>;
