/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */

/**
 * Детальная информация о конкретном нарушении в запросе
 */
export type GlobalErrorResponseOutputDetailsItem = {
  /** Путь к полю в формате dot-notation (например, "user.email") */
  field: string;
  /** Человекочитаемое сообщение о конкретной ошибке в этом поле */
  message: string;
  /** Машиночитаемый код ошибки валидации (например, "invalid_email", "too_short") */
  code: string;
};
