/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import type { HealthResponseOutputInfo } from './healthResponseOutputInfo';
import type { HealthResponseOutputMetrics } from './healthResponseOutputMetrics';
import type { HealthResponseOutputStatus } from './healthResponseOutputStatus';
import type { HealthResponseOutputTime } from './healthResponseOutputTime';

export interface HealthResponseOutput {
  /** Название сервиса */
  service: string;
  /** Текущий статус */
  status: HealthResponseOutputStatus;
  info: HealthResponseOutputInfo;
  time: HealthResponseOutputTime;
  metrics: HealthResponseOutputMetrics;
}
