/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const healthResponseOutputTimeNowRegExp = new RegExp(
  '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
);
export const healthResponseOutputTimeStartedAtRegExp = new RegExp(
  '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
);

export const HealthResponseOutput = zod.object({
  service: zod.string().describe('Название сервиса'),
  status: zod.enum(['up', 'down']).describe('Текущий статус'),
  info: zod.object({
    version: zod.string().describe('Версия приложения'),
    node: zod.string().describe('Версия Node.js'),
    pid: zod.number().describe('ID процесса'),
  }),
  time: zod.object({
    now: zod.iso
      .datetime({})
      .regex(healthResponseOutputTimeNowRegExp)
      .describe('Текущее время сервера'),
    startedAt: zod.iso
      .datetime({})
      .regex(healthResponseOutputTimeStartedAtRegExp)
      .describe('Время старта сервера'),
    uptime: zod.string().describe('Аптайм в формате ч\/м\/с'),
    uptimeSeconds: zod.number().describe('Аптайм в секундах'),
  }),
  metrics: zod.object({
    rss: zod.string().describe('Resident Set Size (общая память)'),
    heapUsed: zod.string().describe('Использованная память в куче'),
    loadAverage: zod.string().describe('Средняя нагрузка на CPU'),
  }),
});

export type HealthResponseOutput = zod.input<typeof HealthResponseOutput>;
export type HealthResponseOutputOutput = zod.output<typeof HealthResponseOutput>;
