/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */

/**
 * Текущий статус
 */
export type HealthResponseOutputStatus =
  (typeof HealthResponseOutputStatus)[keyof typeof HealthResponseOutputStatus];

export const HealthResponseOutputStatus = {
  up: 'up',
  down: 'down',
} as const;
