/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */

export type HealthResponseOutputInfo = {
  /** Версия приложения */
  version: string;
  /** Версия Node.js */
  node: string;
  /** ID процесса */
  pid: number;
};
