/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */

export type HealthResponseOutputMetrics = {
  /** Resident Set Size (общая память) */
  rss: string;
  /** Использованная память в куче */
  heapUsed: string;
  /** Средняя нагрузка на CPU */
  loadAverage: string;
};
