/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const inviteMemberDtoOutputEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$"
);
export const inviteMemberDtoOutputRoleDefault = `member`;
export const InviteMemberDtoOutput = zod.object({
  email: zod
    .email()
    .regex(inviteMemberDtoOutputEmailRegExp)
    .describe('Email пользователя, которого нужно пригласить'),
  role: zod
    .string()
    .default(inviteMemberDtoOutputRoleDefault)
    .describe('Роль, которая будет назначена пользователю после принятия инвайта'),
});

export type InviteMemberDtoOutput = zod.input<typeof InviteMemberDtoOutput>;
export type InviteMemberDtoOutputOutput = zod.output<typeof InviteMemberDtoOutput>;
