/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const MembersControllerUpdateMemberBody = zod.object({
  role: zod.string().optional().describe('Новая роль участника'),
  status: zod.string().optional().describe('Новый статус (active, blocked и т.д.)'),
});

export type MembersControllerUpdateMemberBody = zod.input<typeof MembersControllerUpdateMemberBody>;
export type MembersControllerUpdateMemberBodyOutput = zod.output<
  typeof MembersControllerUpdateMemberBody
>;
