/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const membersControllerInviteBodyEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$"
);
export const membersControllerInviteBodyRoleDefault = `member`;
export const MembersControllerInviteBody = zod.object({
  email: zod
    .email()
    .regex(membersControllerInviteBodyEmailRegExp)
    .describe('Email пользователя, которого нужно пригласить'),
  role: zod
    .string()
    .default(membersControllerInviteBodyRoleDefault)
    .describe('Роль, которая будет назначена пользователю после принятия инвайта'),
});

export type MembersControllerInviteBody = zod.input<typeof MembersControllerInviteBody>;
export type MembersControllerInviteBodyOutput = zod.output<typeof MembersControllerInviteBody>;
