/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const passwordResetConfirmDtoOutputEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$"
);
export const passwordResetConfirmDtoOutputPasswordMin = 8;
export const passwordResetConfirmDtoOutputPasswordMax = 32;

export const PasswordResetConfirmDtoOutput = zod.object({
  email: zod.email().regex(passwordResetConfirmDtoOutputEmailRegExp),
  password: zod
    .string()
    .min(passwordResetConfirmDtoOutputPasswordMin)
    .max(passwordResetConfirmDtoOutputPasswordMax)
    .describe('Новый пароль'),
  confirmPassword: zod.string().describe('Повторите новый пароль'),
});

export type PasswordResetConfirmDtoOutput = zod.input<typeof PasswordResetConfirmDtoOutput>;
export type PasswordResetConfirmDtoOutputOutput = zod.output<typeof PasswordResetConfirmDtoOutput>;
