/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const RefreshTokenResponseOutput = zod
  .object({
    success: zod.boolean().describe('Успешное обновление токенов'),
    token: zod.string().describe('Новый access token (JWT)'),
    message: zod.string().optional().describe('Дополнительное сообщение (опционально)'),
  })
  .describe('Ответ при обновлении пары access\/refresh токенов');

export type RefreshTokenResponseOutput = zod.input<typeof RefreshTokenResponseOutput>;
export type RefreshTokenResponseOutputOutput = zod.output<typeof RefreshTokenResponseOutput>;
