/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const resetPasswordDtoOutputEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$"
);

export const ResetPasswordDtoOutput = zod.object({
  email: zod.email().regex(resetPasswordDtoOutputEmailRegExp).describe('Email для восстановления'),
});

export type ResetPasswordDtoOutput = zod.input<typeof ResetPasswordDtoOutput>;
export type ResetPasswordDtoOutputOutput = zod.output<typeof ResetPasswordDtoOutput>;
