/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const signInDtoOutputEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$"
);

export const SignInDtoOutput = zod
  .object({
    email: zod.email().regex(signInDtoOutputEmailRegExp).describe('Email пользователя'),
    password: zod.string().describe('Пароль пользователя'),
  })
  .describe('Схема входа в систему');

export type SignInDtoOutput = zod.input<typeof SignInDtoOutput>;
export type SignInDtoOutputOutput = zod.output<typeof SignInDtoOutput>;
