/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const signUpDtoOutputEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$"
);
export const signUpDtoOutputPasswordMin = 8;
export const signUpDtoOutputPasswordMax = 32;

export const signUpDtoOutputFirstNameMin = 2;
export const signUpDtoOutputFirstNameMax = 50;

export const signUpDtoOutputLastNameMin = 2;
export const signUpDtoOutputLastNameMax = 50;

export const signUpDtoOutputMiddleNameOneMax = 50;

export const SignUpDtoOutput = zod
  .object({
    email: zod.email().regex(signUpDtoOutputEmailRegExp).describe('Email пользователя'),
    password: zod
      .string()
      .min(signUpDtoOutputPasswordMin)
      .max(signUpDtoOutputPasswordMax)
      .describe('Пароль (минимум 8 символов)'),
    firstName: zod
      .string()
      .min(signUpDtoOutputFirstNameMin)
      .max(signUpDtoOutputFirstNameMax)
      .describe('Имя'),
    lastName: zod
      .string()
      .min(signUpDtoOutputLastNameMin)
      .max(signUpDtoOutputLastNameMax)
      .describe('Фамилия'),
    middleName: zod
      .union([zod.string().max(signUpDtoOutputMiddleNameOneMax), zod.enum([''])])
      .optional()
      .describe('Отчество (опционально)'),
  })
  .describe('Схема регистрации пользователя');

export type SignUpDtoOutput = zod.input<typeof SignUpDtoOutput>;
export type SignUpDtoOutputOutput = zod.output<typeof SignUpDtoOutput>;
