/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */

/**
 * Схема регистрации пользователя
 */
export interface SignUpDtoOutput {
  /**
   * Email пользователя
   * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
   */
  email: string;
  /**
   * Пароль (минимум 8 символов)
   * @minLength 8
   * @maxLength 32
   */
  password: string;
  /**
   * Имя
   * @minLength 2
   * @maxLength 50
   */
  firstName: string;
  /**
   * Фамилия
   * @minLength 2
   * @maxLength 50
   */
  lastName: string;
  /** Отчество (опционально) */
  middleName?: string | '';
}
