/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const syncTagsDtoOutputTagsMax = 15;

export const SyncTagsDtoOutput = zod.object({
  tags: zod
    .array(zod.string())
    .min(1)
    .max(syncTagsDtoOutputTagsMax)
    .describe(
      'Массив названий тегов для привязки к команде. Если тега нет в базе, он будет создан.'
    ),
});

export type SyncTagsDtoOutput = zod.input<typeof SyncTagsDtoOutput>;
export type SyncTagsDtoOutputOutput = zod.output<typeof SyncTagsDtoOutput>;
