/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const TeamsControllerFindOne200 = zod.looseObject({});

export type TeamsControllerFindOne200 = zod.input<typeof TeamsControllerFindOne200>;
export type TeamsControllerFindOne200Output = zod.output<typeof TeamsControllerFindOne200>;
