/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const TeamsControllerUpdateTeamAvatarBody = zod
  .object({
    file: zod.instanceof(File).optional().describe('Файл изображения аватара команды'),
  })
  .describe('Тело запроса обновления аватара команды (multipart\/form-data)');

export type TeamsControllerUpdateTeamAvatarBody = zod.input<
  typeof TeamsControllerUpdateTeamAvatarBody
>;
export type TeamsControllerUpdateTeamAvatarBodyOutput = zod.output<
  typeof TeamsControllerUpdateTeamAvatarBody
>;
