/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const teamsControllerSyncTagsBodyTagsMax = 15;

export const TeamsControllerSyncTagsBody = zod.object({
  tags: zod
    .array(zod.string())
    .min(1)
    .max(teamsControllerSyncTagsBodyTagsMax)
    .describe(
      'Массив названий тегов для привязки к команде. Если тега нет в базе, он будет создан.'
    ),
});

export type TeamsControllerSyncTagsBody = zod.input<typeof TeamsControllerSyncTagsBody>;
export type TeamsControllerSyncTagsBodyOutput = zod.output<typeof TeamsControllerSyncTagsBody>;
