/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const teamsControllerCreateBodyNameMin = 2;
export const teamsControllerCreateBodyNameMax = 100;

export const teamsControllerCreateBodyDescriptionMax = 500;

export const TeamsControllerCreateBody = zod.object({
  name: zod
    .string()
    .min(teamsControllerCreateBodyNameMin)
    .max(teamsControllerCreateBodyNameMax)
    .describe('Название команды, отображаемое в интерфейсе'),
  description: zod
    .string()
    .max(teamsControllerCreateBodyDescriptionMax)
    .optional()
    .describe('Краткое описание деятельнос��и или целей команды'),
  slug: zod.string().optional().describe('Уникальная ссылка на изображение команду'),
  tags: zod
    .array(zod.string())
    .optional()
    .describe('Список строковых названий тегов для классификации'),
});

export type TeamsControllerCreateBody = zod.input<typeof TeamsControllerCreateBody>;
export type TeamsControllerCreateBodyOutput = zod.output<typeof TeamsControllerCreateBody>;
