/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const TeamsControllerUpdateTeamBannerBody = zod
  .object({
    file: zod.instanceof(File).optional().describe('Файл изображения баннера команды'),
  })
  .describe('Тело запроса обновления баннера команды (multipart\/form-data)');

export type TeamsControllerUpdateTeamBannerBody = zod.input<
  typeof TeamsControllerUpdateTeamBannerBody
>;
export type TeamsControllerUpdateTeamBannerBodyOutput = zod.output<
  typeof TeamsControllerUpdateTeamBannerBody
>;
