/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const teamsControllerUpdateBodyNameMin = 2;
export const teamsControllerUpdateBodyNameMax = 100;

export const teamsControllerUpdateBodyDescriptionMax = 500;

export const TeamsControllerUpdateBody = zod.object({
  name: zod
    .string()
    .min(teamsControllerUpdateBodyNameMin)
    .max(teamsControllerUpdateBodyNameMax)
    .optional()
    .describe('Название команды, отображаемое в интерфейсе'),
  description: zod
    .string()
    .max(teamsControllerUpdateBodyDescriptionMax)
    .optional()
    .describe('Краткое описание деятельнос��и или целей команды'),
  slug: zod.string().optional().describe('Уникальная ссылка на изображение команду'),
  tags: zod
    .array(zod.string())
    .optional()
    .describe('Список строковых названий тегов для классификации'),
});

export type TeamsControllerUpdateBody = zod.input<typeof TeamsControllerUpdateBody>;
export type TeamsControllerUpdateBodyOutput = zod.output<typeof TeamsControllerUpdateBody>;
