/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const teamMemberResponseOutputInitialsMax = 2;

export const teamMemberResponseOutputJoinedAtRegExp = new RegExp(
  '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
);

export const TeamMemberResponseOutput = zod.object({
  id: zod.string().describe('Уникальный ID пользователя (UUID или ULID)'),
  role: zod
    .enum(['owner', 'admin', 'member'])
    .describe('Роль участника в рамках конкретной команды'),
  status: zod
    .enum(['active', 'pending', 'blocked'])
    .describe('Текущий статус членства (активен, ожидает приглашения, заблокирован)'),
  fullName: zod.string().describe('Полное имя для отображения (Фамилия Имя Отчество)'),
  firstName: zod.string().describe('Имя пользователя'),
  lastName: zod.string().describe('Фамилия пользователя'),
  avatarUrl: zod
    .url()
    .nullable()
    .describe('Прямая ссылка на изображение профиля или null, если не задано'),
  initials: zod
    .string()
    .max(teamMemberResponseOutputInitialsMax)
    .describe('Две буквы для аватара-заглушки (например, \"ИИ\")'),
  joinedAt: zod.iso
    .datetime({})
    .regex(teamMemberResponseOutputJoinedAtRegExp)
    .describe('Дата и время вступления в команду в формате ISO 8601'),
});

export type TeamMemberResponseOutput = zod.input<typeof TeamMemberResponseOutput>;
export type TeamMemberResponseOutputOutput = zod.output<typeof TeamMemberResponseOutput>;
