/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */

/**
 * Схема для частичного обновления данных профиля
 */
export interface UpdateProfileDtoOutput {
  /**
   * @minLength 1
   * @maxLength 50
   */
  firstName?: string;
  /**
   * @minLength 1
   * @maxLength 50
   */
  lastName?: string;
  /**
   * @maxLength 50
   * @nullable
   */
  middleName?: string | null;
  /**
   * @maxLength 1000
   * @nullable
   */
  bio?: string | null;
  /** @maxLength 50 */
  timezone?: string;
  /**
   * @minLength 2
   * @maxLength 2
   */
  language?: string;
}
