/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const updateTeamDtoOutputNameMin = 2;
export const updateTeamDtoOutputNameMax = 100;

export const updateTeamDtoOutputDescriptionMax = 500;

export const UpdateTeamDtoOutput = zod.object({
  name: zod
    .string()
    .min(updateTeamDtoOutputNameMin)
    .max(updateTeamDtoOutputNameMax)
    .optional()
    .describe('Название команды, отображаемое в интерфейсе'),
  description: zod
    .string()
    .max(updateTeamDtoOutputDescriptionMax)
    .optional()
    .describe('Краткое описание деятельнос��и или целей команды'),
  slug: zod.string().optional().describe('Уникальная ссылка на изображение команду'),
  tags: zod
    .array(zod.string())
    .optional()
    .describe('Список строковых названий тегов для классификации'),
});

export type UpdateTeamDtoOutput = zod.input<typeof UpdateTeamDtoOutput>;
export type UpdateTeamDtoOutputOutput = zod.output<typeof UpdateTeamDtoOutput>;
