/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const updateProfileDtoOutputFirstNameMax = 50;

export const updateProfileDtoOutputLastNameMax = 50;

export const updateProfileDtoOutputMiddleNameMax = 50;

export const updateProfileDtoOutputBioMax = 1000;

export const updateProfileDtoOutputTimezoneMax = 50;

export const updateProfileDtoOutputLanguageMin = 2;
export const updateProfileDtoOutputLanguageMax = 2;

export const UpdateProfileDtoOutput = zod
  .object({
    firstName: zod.string().min(1).max(updateProfileDtoOutputFirstNameMax).optional(),
    lastName: zod.string().min(1).max(updateProfileDtoOutputLastNameMax).optional(),
    middleName: zod.string().max(updateProfileDtoOutputMiddleNameMax).nullish(),
    bio: zod.string().max(updateProfileDtoOutputBioMax).nullish(),
    timezone: zod.string().max(updateProfileDtoOutputTimezoneMax).optional(),
    language: zod
      .string()
      .min(updateProfileDtoOutputLanguageMin)
      .max(updateProfileDtoOutputLanguageMax)
      .optional(),
  })
  .describe('Схема для частичного обновления данных профиля');

export type UpdateProfileDtoOutput = zod.input<typeof UpdateProfileDtoOutput>;
export type UpdateProfileDtoOutputOutput = zod.output<typeof UpdateProfileDtoOutput>;
