/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import type { UpdateNotificationsDtoOutputEmail } from './updateNotificationsDtoOutputEmail';
import type { UpdateNotificationsDtoOutputPush } from './updateNotificationsDtoOutputPush';

/**
 * Схема для частичного обновления настроек уведомлений
 */
export interface UpdateNotificationsDtoOutput {
  email?: UpdateNotificationsDtoOutputEmail;
  push?: UpdateNotificationsDtoOutputPush;
}
