/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */

export type UpdateNotificationsDtoOutputEmail = {
  /** Уведомление на почту при назначении задачи */
  task_assigned: boolean;
  /** Уведомление на почту при упоминании в комментариях */
  mentions: boolean;
  /** Ежедневная сводка задач на почту */
  daily_summary: boolean;
};
