/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const userTeamResponseOutputIdRegExp = new RegExp(
  '^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$'
);
export const userTeamResponseOutputJoinedAtRegExp = new RegExp(
  '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
);

export const UserTeamResponseOutput = zod.object({
  id: zod.uuid().regex(userTeamResponseOutputIdRegExp).describe('Уникальный ID команды'),
  name: zod.string().describe('Название команды'),
  slug: zod.string().describe('Уникальный URL-путь команды'),
  description: zod.string().nullable().describe('Краткое описание команды'),
  avatarUrl: zod.string().nullable().describe('URL изображения профиля команды'),
  role: zod.string().describe('Системное название роли пользователя'),
  joinedAt: zod.iso
    .datetime({})
    .regex(userTeamResponseOutputJoinedAtRegExp)
    .describe('Дата, когда пользователь вступил в команду'),
  permissions: zod
    .object({
      canEdit: zod.boolean().describe('Разрешено ли редактировать настройки и профиль команды'),
      canDelete: zod
        .boolean()
        .describe('Разрешено ли полностью удалить команду (только для владельца)'),
      canManageMembers: zod.boolean().describe('Разрешено ли менять роли и исключать участников'),
      canInvite: zod.boolean().describe('Разрешено ли приглашать новых участников'),
      isOwner: zod.boolean().describe('Является ли текущий пользователь владельцем (Owner)'),
    })
    .describe('Объект прав доступа текущего пользователя'),
});

export type UserTeamResponseOutput = zod.input<typeof UserTeamResponseOutput>;
export type UserTeamResponseOutputOutput = zod.output<typeof UserTeamResponseOutput>;
