/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const UserControllerUploadAvatarBody = zod
  .object({
    file: zod.instanceof(File).optional().describe('Файл изображения аватара'),
  })
  .describe('Тело запроса загрузки аватара пользователя (multipart\/form-data)');

export type UserControllerUploadAvatarBody = zod.input<typeof UserControllerUploadAvatarBody>;
export type UserControllerUploadAvatarBodyOutput = zod.output<
  typeof UserControllerUploadAvatarBody
>;
