/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */

export type UserResponseOutputNotificationsPush = {
  /** Push-уведомление при назначении задачи */
  task_assigned: boolean;
  /** Push-уведомления о дедлайнах */
  reminders: boolean;
};
