/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import type { UserResponseOutputNotificationsEmail } from './userResponseOutputNotificationsEmail';
import type { UserResponseOutputNotificationsPush } from './userResponseOutputNotificationsPush';

/**
 * Настройки уведомлений пользователя
 */
export type UserResponseOutputNotifications = {
  email: UserResponseOutputNotificationsEmail;
  push: UserResponseOutputNotificationsPush;
};
