/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const userResponseOutputEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$"
);
export const userResponseOutputProfileCreatedAtRegExp = new RegExp(
  '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
);
export const userResponseOutputProfileUpdatedAtRegExp = new RegExp(
  '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
);
export const userResponseOutputSecurityLastPasswordChangeRegExp = new RegExp(
  '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
);

export const UserResponseOutput = zod.object({
  id: zod.string().describe('Уникальный идентификатор (CUID\/UUID)'),
  email: zod.email().regex(userResponseOutputEmailRegExp).describe('Электронная почта'),
  profile: zod.object({
    firstName: zod.string().describe('Имя пользователя'),
    lastName: zod.string().describe('Фамилия'),
    middleName: zod.string().nullable().describe('Отчество'),
    bio: zod.string().nullable().describe('О себе'),
    avatarUrl: zod.url().nullable().describe('Ссылка на аватар в S3'),
    timezone: zod.string().describe('Временная зона'),
    language: zod.string().describe('Язык интерфейса'),
    createdAt: zod.iso
      .datetime({})
      .regex(userResponseOutputProfileCreatedAtRegExp)
      .describe('Дата регистрации'),
    updatedAt: zod.iso
      .datetime({})
      .regex(userResponseOutputProfileUpdatedAtRegExp)
      .describe('Дата последнего обновления профиля'),
  }),
  security: zod
    .object({
      is2faEnabled: zod.boolean().describe('Статус двухфакторной аутентификации'),
      lastPasswordChange: zod.iso
        .datetime({})
        .regex(userResponseOutputSecurityLastPasswordChangeRegExp)
        .describe('Дата последнего изменения пароля'),
    })
    .describe('Данные безопасности аккаунта'),
  notifications: zod
    .object({
      email: zod.object({
        task_assigned: zod.boolean().describe('Уведомление на п��чту при назначении задачи'),
        mentions: zod.boolean().describe('Уведомление на почту при упоминании в комментариях'),
        daily_summary: zod.boolean().describe('Ежедневная сводка задач на почту'),
      }),
      push: zod.object({
        task_assigned: zod.boolean().describe('Push-уведомление при назначении задачи'),
        reminders: zod.boolean().describe('Push-уведомления о дедлайнах'),
      }),
    })
    .describe('Настройки уведомлений пользователя'),
});

export type UserResponseOutput = zod.input<typeof UserResponseOutput>;
export type UserResponseOutputOutput = zod.output<typeof UserResponseOutput>;
