/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import type { UserResponseOutputNotifications } from './userResponseOutputNotifications';
import type { UserResponseOutputProfile } from './userResponseOutputProfile';
import type { UserResponseOutputSecurity } from './userResponseOutputSecurity';

export interface UserResponseOutput {
  /** Уникальный идентификатор (CUID/UUID) */
  id: string;
  /**
   * Электронная почта
   * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
   */
  email: string;
  profile: UserResponseOutputProfile;
  /** Данные безопасности аккаунта */
  security: UserResponseOutputSecurity;
  /** Настройки уведомлений пользователя */
  notifications: UserResponseOutputNotifications;
}
