/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const UserControllerUpdateNotificationsBody = zod
  .object({
    email: zod
      .object({
        task_assigned: zod.boolean().describe('Уведомление на п��чту при назначении задачи'),
        mentions: zod.boolean().describe('Уведомление на почту при упоминании в комментариях'),
        daily_summary: zod.boolean().describe('Ежедневная сводка задач на почту'),
      })
      .optional(),
    push: zod
      .object({
        task_assigned: zod.boolean().describe('Push-уведомление при назначении задачи'),
        reminders: zod.boolean().describe('Push-уведомления о дедлайнах'),
      })
      .optional(),
  })
  .describe('Схема для частичного обновления настроек уведомлений');

export type UserControllerUpdateNotificationsBody = zod.input<
  typeof UserControllerUpdateNotificationsBody
>;
export type UserControllerUpdateNotificationsBodyOutput = zod.output<
  typeof UserControllerUpdateNotificationsBody
>;
