/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const userControllerUpdateProfileBodyFirstNameMax = 50;

export const userControllerUpdateProfileBodyLastNameMax = 50;

export const userControllerUpdateProfileBodyMiddleNameMax = 50;

export const userControllerUpdateProfileBodyBioMax = 1000;

export const userControllerUpdateProfileBodyTimezoneMax = 50;

export const userControllerUpdateProfileBodyLanguageMin = 2;
export const userControllerUpdateProfileBodyLanguageMax = 2;

export const UserControllerUpdateProfileBody = zod
  .object({
    firstName: zod.string().min(1).max(userControllerUpdateProfileBodyFirstNameMax).optional(),
    lastName: zod.string().min(1).max(userControllerUpdateProfileBodyLastNameMax).optional(),
    middleName: zod.string().max(userControllerUpdateProfileBodyMiddleNameMax).nullish(),
    bio: zod.string().max(userControllerUpdateProfileBodyBioMax).nullish(),
    timezone: zod.string().max(userControllerUpdateProfileBodyTimezoneMax).optional(),
    language: zod
      .string()
      .min(userControllerUpdateProfileBodyLanguageMin)
      .max(userControllerUpdateProfileBodyLanguageMax)
      .optional(),
  })
  .describe('Схема для частичного обновления данных профиля');

export type UserControllerUpdateProfileBody = zod.input<typeof UserControllerUpdateProfileBody>;
export type UserControllerUpdateProfileBodyOutput = zod.output<
  typeof UserControllerUpdateProfileBody
>;
