/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */

export type UserControllerGetActivityParams = {
  /**
   * @minimum 1
   * @maximum 9007199254740991
   */
  page?: number;
  /**
   * Количество записей для вывода (по умолчанию 10)
   * @minimum 1
   * @maximum 100
   */
  limit?: string;
};
