/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const userControllerGetActivityParamsPageDefault = 1;
export const userControllerGetActivityParamsPageMax = 9007199254740991;

export const userControllerGetActivityParamsLimitDefault = 20;
export const userControllerGetActivityParamsLimitMax = 100;

export const UserControllerGetActivityParams = zod.object({
  page: zod
    .number()
    .min(1)
    .max(userControllerGetActivityParamsPageMax)
    .default(userControllerGetActivityParamsPageDefault),
  limit: zod
    .number()
    .min(1)
    .max(userControllerGetActivityParamsLimitMax)
    .default(userControllerGetActivityParamsLimitDefault),
});

export type UserControllerGetActivityParams = zod.input<typeof UserControllerGetActivityParams>;
export type UserControllerGetActivityParamsOutput = zod.output<
  typeof UserControllerGetActivityParams
>;
