/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const userInviteResponseOutputExpiresAtRegExp = new RegExp(
  '^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))T(?:(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d(?:\\.\\d+)?)?(?:Z))$'
);

export const UserInviteResponseOutput = zod.object({
  code: zod.string().describe('Код инвайта'),
  teamName: zod.string().describe('Название команды'),
  teamAvatar: zod.string().nullable().describe('Аватар команды'),
  role: zod.string().describe('Роль'),
  inviterName: zod.string().describe('Имя пригласившего'),
  expiresAt: zod.iso
    .datetime({})
    .regex(userInviteResponseOutputExpiresAtRegExp)
    .describe('Дата истечения'),
});

export type UserInviteResponseOutput = zod.input<typeof UserInviteResponseOutput>;
export type UserInviteResponseOutputOutput = zod.output<typeof UserInviteResponseOutput>;
