/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const verifyDtoOutputEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$"
);
export const verifyDtoOutputCodeMin = 6;
export const verifyDtoOutputCodeMax = 6;

export const VerifyDtoOutput = zod
  .object({
    email: zod
      .email()
      .regex(verifyDtoOutputEmailRegExp)
      .describe('Email пользователя, на который был отправлен код'),
    code: zod
      .string()
      .min(verifyDtoOutputCodeMin)
      .max(verifyDtoOutputCodeMax)
      .describe('6-значный OTP код подтверждения'),
  })
  .describe('Схема верификации OTP кода');

export type VerifyDtoOutput = zod.input<typeof VerifyDtoOutput>;
export type VerifyDtoOutputOutput = zod.output<typeof VerifyDtoOutput>;
