/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * Task Tracker API
 * API бэкенда таск-трекера
 * OpenAPI spec version: 0.1.0
 */
import { z as zod } from 'zod';

export const verifyResetCodeDtoOutputEmailRegExp = new RegExp(
  "^(?!\\.)(?!.\*\\.\\.)([A-Za-z0-9_'+\\-\\.]\*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\\-]\*\\.)+[A-Za-z]{2,}$"
);
export const verifyResetCodeDtoOutputCodeMin = 6;
export const verifyResetCodeDtoOutputCodeMax = 6;

export const VerifyResetCodeDtoOutput = zod.object({
  email: zod.email().regex(verifyResetCodeDtoOutputEmailRegExp),
  code: zod
    .string()
    .min(verifyResetCodeDtoOutputCodeMin)
    .max(verifyResetCodeDtoOutputCodeMax)
    .describe('Код из письма'),
});

export type VerifyResetCodeDtoOutput = zod.input<typeof VerifyResetCodeDtoOutput>;
export type VerifyResetCodeDtoOutputOutput = zod.output<typeof VerifyResetCodeDtoOutput>;
