name: CI workflow

on:
  push:
    branches:
      - main
      - dev
      - "feat/**"
      - "fix/**"
      - "refactor/**"
      - "chore/**"
      - "perf/**"
      - "build/**"
      - "ci/**"
    paths-ignore:
      - "**.md"
      - "infra/**"
      - ".gitignore"
      - "docker-compose.yml"

  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - "**.md"
      - "infra/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Lint FSD
        run: pnpm lint:fsd

      - name: Format
        run: pnpm format:check

      - name: Typecheck
        run: pnpm typecheck

      - name: Unit tests
        run: pnpm test:ci
        env:
          NODE_ENV: test

      - name: Build
        run: pnpm build
        env:
          SKIP_ENV_VALIDATION: true
          NODE_ENV: production
          NEXT_PUBLIC_API_BASE_URL: ${{ vars.NEXT_PUBLIC_API_BASE_URL }}
          NEXT_PUBLIC_APP_URL: ${{vars.NEXT_PUBLIC_APP_URL}}
          NEXT_PUBLIC_FARO_URL: ${{ vars.NEXT_PUBLIC_FARO_URL }}
          NEXT_PUBLIC_FARO_APP_VERSION: ${{ vars.NEXT_PUBLIC_FARO_APP_VERSION }}
          NEXT_PUBLIC_APP_ENV: ${{ vars.NEXT_PUBLIC_APP_ENV }}
          NEXT_PUBLIC_FARO_APP_NAME: ${{ vars.NEXT_PUBLIC_FARO_APP_NAME }}
          NEXT_PUBLIC_FARO_APP_NAMESPACE: ${{ vars.NEXT_PUBLIC_FARO_APP_NAMESPACE }}
          NEXT_PUBLIC_METRICS_ENABLED: ${{vars.NEXT_PUBLIC_METRICS_ENABLED}}
    #      - name: Build Storybook
    #        run: pnpm build-storybook
